---
SAGEMAKER_SHARED_S3_PREFIX: "data-54d65034-0193-46f1-9ac7-b6dc1d20d6f6/models/c93cbf5a-6ed8-43fa-94b1-208195fe4520/sagemaker-robomaker-artifacts"
CAR_NAME: "AllTheToys"
KINESIS_VIDEO_STREAM_NAME: "dr-kvs-372026249783-20230325194552-c084bb3f-8100-45ea-b4a7-be06b50c338a"
TRAINING_JOB_ARN: "arn:aws:deepracer:us-east-1:981162992383:training_job/3DLO1y8wR1-gPqQqZ_k4Vw"
REWARD_FILE_S3_KEY: "data-54d65034-0193-46f1-9ac7-b6dc1d20d6f6/models/c93cbf5a-6ed8-43fa-94b1-208195fe4520/reward_function.py"
MP4_S3_OBJECT_PREFIX: "data-54d65034-0193-46f1-9ac7-b6dc1d20d6f6/models/c93cbf5a-6ed8-43fa-94b1-208195fe4520/videos/training/training-20230325194552-3DLO1y8wR1-gPqQqZ_k4Vw"
WORLD_NAME: "reInvent2019_wide"
SAGEMAKER_SHARED_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
RACE_TYPE: "TIME_TRIAL"
MODEL_METADATA_FILE_S3_KEY: "data-54d65034-0193-46f1-9ac7-b6dc1d20d6f6/models/c93cbf5a-6ed8-43fa-94b1-208195fe4520/model_metadata.json"
BODY_SHELL_TYPE: "f1_car_clown_01"
TARGET_REWARD_SCORE: "None"
CHANGE_START_POSITION: "true"
METRICS_S3_OBJECT_KEY: "data-54d65034-0193-46f1-9ac7-b6dc1d20d6f6/models/c93cbf5a-6ed8-43fa-94b1-208195fe4520/metrics/training/training-20230325194552-3DLO1y8wR1-gPqQqZ_k4Vw.json"
AWS_REGION: "us-east-1"
NUMBER_OF_EPISODES: "0"
S3_KMS_CMK_ARN: "arn:aws:kms:us-east-1:372026249783:key/c5ac27ef-a9f7-40ea-8a9e-7dcdcf215090"
METRIC_NAMESPACE: "AWSDeepRacer"
ALTERNATE_DRIVING_DIRECTION: "false"
ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID: "372026249783"
SIMTRACE_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
METRICS_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
MP4_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
SIMTRACE_S3_PREFIX: "data-54d65034-0193-46f1-9ac7-b6dc1d20d6f6/models/c93cbf5a-6ed8-43fa-94b1-208195fe4520/sim-trace/training"
JOB_TYPE: "TRAINING"
TRACK_DIRECTION_CLOCKWISE: "false"
METRIC_NAME: "TrainingRewardScore"
